=== bvsslgayathri/sem6/college.dtd
<!ELEMENT college (teach,non-teach,student)>
<!ELEMENT teach (teaching,teaching,teaching)>
<!ELEMENT teaching (name,id,dept)>
<!ELEMENT non-teach (nonteaching,nonteaching)>
<!ELEMENT nonteaching (name,id,dept)>
<!ELEMENT student (students,students)>
<!ELEMENT students (name,roll,dept)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT roll (#PCDATA)>
<!ELEMENT dept (#PCDATA)>
<!ATTLIST teach category CDATA "teaching">
<!ATTLIST non-teach category CDATA "non teaching">
<!ATTLIST student category CDATA "student">

=== bvsslgayathri/sem6/week 5/sample.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="college.css"?>   

<!--sdhbbcs-->
<?xml-stylesheet type="text/xsl" href="sample.xsl"?>
<!-- <!DOCTYPE college SYSTEM "college.dtd"> -->
<college xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="college.xsd">   
   <teach category="teaching">  
        <teaching>
        <name>Rohit Sir</name>
        <id>1</id>
        <dept>cse</dept>
        </teaching>
        <teaching>
        <name>Akhila mam</name>
        <id>1</id>
        <dept>cse</dept>
        </teaching>
        <teaching>
        <name>xyz</name>
        <id>1</id>
        <dept>cse</dept>
        </teaching>
   </teach>   
   <non-teach category="non-teaching">   
        <nonteaching>
        <name>xyz</name>
        <id>2</id>
        <dept>office staff</dept>
        </nonteaching>
        <nonteaching>
        <name>xyz</name>
        <id>2</id>
        <dept>office staff</dept>
        </nonteaching>
   </non-teach>   
   <student category="student">   
        <students>
           <name>gayathri</name>
            <roll>19-5p1</roll>
            <dept>cse</dept>
        </students>
        <students >
           <name>abc</name>
            <roll>19-5p1</roll>
            <dept>cse</dept>
        </students>
   </student>   
</college>
